### ISSUE TITLE
Feed Back code review from Nich and Shaughn

### ISSUE THREAD

**Issue by nichgalzin** [carlosalbertobuitragosantamaria/api#59]
Site look neats, like the neon look. Code is well laid out and organized. Like how the js files are organized.

Thoughts:
-Could do more with the unsplash pictures things. Maybe a train photo slide or something?
-Horizontal slide bar is a little hard to find and work. 
-Radio buttons work on click without a further button?
- Site looks very strange in Edge browser
- Readme file:
    -Commands for cloning repo didn't work
    -Add a bit about running in Live server as modules didn't load right otherwise.

**Comment by yuqingwwang** [comment]
thank you for the review @nichgalzin, could you attach a screenshot of the page on Edge please? We couldn't reproduce the error 😢

For radio button part 🔘 (changed!)
- ~~Finsbury Park is selected as default, so its departure times will show up when the user hasn't changed the station selected and click on "click here";~~
- ~~we considered using search bar or drop menu but the intention of using radio buttons was to mimic the tube map. Sadly didn't figure out a way to do a clickable image (probably too much work) .~~

And for problems cloning, you might need to [install GitHub CLI](https://github.com/cli/cli/tree/trunk) first. 
~~I will update the README soon.~~
